
export const ALL_CATEGORIES_REQUEST = "ALL_CATEGORIES_REQUEST";
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS";
export const ALL_CATEGORIES_FAIL = "ALL_CATEGORIES_FAIL";


export const NEW_CATEGORIES_REQUEST = "NEW_CATEGORIES_REQUEST";
export const NEW_CATEGORIES_SUCCESS = "NEW_CATEGORIES_SUCCESS";
export const NEW_CATEGORIES_RESET = "NEW_CATEGORIES_RESET";
export const NEW_CATEGORIES_FAIL = "NEW_CATEGORIES_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

