
export const ALL_CATEGORIES_REQUEST = "ALL_CATEGORIES_REQUEST";
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS";
export const ALL_CATEGORIES_FAIL = "ALL_CATEGORIES_FAIL";


export const NEW_CATEGORIES_REQUEST = "NEW_CATEGORIES_REQUEST";
export const NEW_CATEGORIES_SUCCESS = "NEW_CATEGORIES_SUCCESS";
export const NEW_CATEGORIES_RESET = "NEW_CATEGORIES_RESET";
export const NEW_CATEGORIES_FAIL = "NEW_CATEGORIES_FAIL";


export const ALL_MAINCATEGORIES_REQUEST = "ALL_MAINCATEGORIES_REQUEST";
export const ALL_MAINCATEGORIES_SUCCESS = "ALL_MAINCATEGORIES_SUCCESS";
export const ALL_MAINCATEGORIES_FAIL = "ALL_MAINCATEGORIES_FAIL";

export const MAINCATEGORIES_DETAILS_REQUEST = "MAINCATEGORIES_DETAILS_REQUEST";
export const MAINCATEGORIES_DETAILS_SUCCESS = "MAINCATEGORIES_DETAILS_SUCCESS";
export const MAINCATEGORIES_DETAILS_FAIL = "MAINCATEGORIES_DETAILS_FAIL";

export const UPDATE_MAINCATEGORIES_REQUEST = "UPDATE_MAINCATEGORIES_REQUEST";
export const UPDATE_MAINCATEGORIES_SUCCESS = "UPDATE_MAINCATEGORIES_SUCCESS";
export const UPDATE_MAINCATEGORIES_RESET = "UPDATE_MAINCATEGORIES_RESET";
export const UPDATE_MAINCATEGORIES_FAIL = "UPDATE_MAINCATEGORIES_FAIL";

export const DELETE_MAINCATEGORIES_REQUEST = "DELETE_MAINCATEGORIES_REQUEST";
export const DELETE_MAINCATEGORIES_SUCCESS = "DELETE_MAINCATEGORIES_SUCCESS";
export const DELETE_MAINCATEGORIES_RESET = "DELETE_MAINCATEGORIES_RESET";
export const DELETE_MAINCATEGORIES_FAIL = "DELETE_MAINCATEGORIES_FAIL";

export const NEW_MAINCATEGORIES_REQUEST = "NEW_MAINCATEGORIES_REQUEST";
export const NEW_MAINCATEGORIES_SUCCESS = "NEW_MAINCATEGORIES_SUCCESS";
export const NEW_MAINCATEGORIES_RESET = "NEW_MAINCATEGORIES_RESET";
export const NEW_MAINCATEGORIES_FAIL = "NEW_MAINCATEGORIES_FAIL";


export const ALL_SUBCATEGORIES_REQUEST = "ALL_SUBCATEGORIES_REQUEST";
export const ALL_SUBCATEGORIES_SUCCESS = "ALL_SUBCATEGORIES_SUCCESS";
export const ALL_SUBCATEGORIES_FAIL = "ALL_SUBCATEGORIES_FAIL";

export const NEW_SUBCATEGORIES_REQUEST = "NEW_SUBCATEGORIES_REQUEST";
export const NEW_SUBCATEGORIES_SUCCESS = "NEW_SUBCATEGORIES_SUCCESS";
export const NEW_SUBCATEGORIES_RESET = "NEW_SUBCATEGORIES_RESET";
export const NEW_SUBCATEGORIES_FAIL = "NEW_SUBCATEGORIES_FAIL";

export const UPDATE_SUBCATEGORIES_REQUEST = "UPDATE_SUBCATEGORIES_REQUEST";
export const UPDATE_SUBCATEGORIES_SUCCESS = "UPDATE_SUBCATEGORIES_SUCCESS";
export const UPDATE_SUBCATEGORIES_RESET = "UPDATE_SUBCATEGORIES_RESET";
export const UPDATE_SUBCATEGORIES_FAIL = "UPDATE_SUBCATEGORIES_FAIL";

export const DELETE_SUBCATEGORIES_REQUEST = "DELETE_SUBCATEGORIES_REQUEST";
export const DELETE_SUBCATEGORIES_SUCCESS = "DELETE_SUBCATEGORIES_SUCCESS";
export const DELETE_SUBCATEGORIES_RESET = "DELETE_SUBCATEGORIES_RESET";
export const DELETE_SUBCATEGORIES_FAIL = "DELETE_SUBCATEGORIES_FAIL";

export const SUBCATEGORIES_DETAILS_REQUEST = "SUBCATEGORIES_DETAILS_REQUEST";
export const SUBCATEGORIES_DETAILS_SUCCESS = "SUBCATEGORIES_DETAILS_SUCCESS";
export const SUBCATEGORIES_DETAILS_FAIL = "SUBCATEGORIES_DETAILS_FAIL";

export const ALL_CHILDSUBCATEGORIES_REQUEST = "ALL_CHILDSUBCATEGORIES_REQUEST";
export const ALL_CHILDSUBCATEGORIES_SUCCESS = "ALL_CHILDSUBCATEGORIES_SUCCESS";
export const ALL_CHILDSUBCATEGORIES_FAIL = "ALL_CHILDSUBCATEGORIES_FAIL";

export const NEW_CHILDSUBCATEGORIES_REQUEST = "NEW_CHILDSUBCATEGORIES_REQUEST";
export const NEW_CHILDSUBCATEGORIES_SUCCESS = "NEW_CHILDSUBCATEGORIES_SUCCESS";
export const NEW_CHILDSUBCATEGORIES_RESET = "NEW_CHILDSUBCATEGORIES_RESET";
export const NEW_CHILDSUBCATEGORIES_FAIL = "NEW_CHILDSUBCATEGORIES_FAIL";

export const UPDATE_CHILDSUBCATEGORIES_REQUEST = "UPDATE_CHILDSUBCATEGORIES_REQUEST";
export const UPDATE_CHILDSUBCATEGORIES_SUCCESS = "UPDATE_CHILDSUBCATEGORIES_SUCCESS";
export const UPDATE_CHILDSUBCATEGORIES_RESET = "UPDATE_CHILDSUBCATEGORIES_RESET";
export const UPDATE_CHILDSUBCATEGORIES_FAIL = "UPDATE_CHILDSUBCATEGORIES_FAIL";

export const DELETE_CHILDSUBCATEGORIES_REQUEST = "DELETE_CHILDSUBCATEGORIES_REQUEST";
export const DELETE_CHILDSUBCATEGORIES_SUCCESS = "DELETE_CHILDSUBCATEGORIES_SUCCESS";
export const DELETE_CHILDSUBCATEGORIES_RESET = "DELETE_CHILDSUBCATEGORIES_RESET";
export const DELETE_CHILDSUBCATEGORIES_FAIL = "DELETE_CHILDSUBCATEGORIES_FAIL";

export const CHILDSUBCATEGORIES_DETAILS_REQUEST = "CHILDSUBCATEGORIES_DETAILS_REQUEST";
export const CHILDSUBCATEGORIES_DETAILS_SUCCESS = "CHILDSUBCATEGORIES_DETAILS_SUCCESS";
export const CHILDSUBCATEGORIES_DETAILS_FAIL = "CHILDSUBCATEGORIES_DETAILS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

