
export const ALL_CATEGORIES_REQUEST = "ALL_CATEGORIES_REQUEST";
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS";
export const ALL_CATEGORIES_FAIL = "ALL_CATEGORIES_FAIL";


export const NEW_CATEGORIES_REQUEST = "NEW_CATEGORIES_REQUEST";
export const NEW_CATEGORIES_SUCCESS = "NEW_CATEGORIES_SUCCESS";
export const NEW_CATEGORIES_RESET = "NEW_CATEGORIES_RESET";
export const NEW_CATEGORIES_FAIL = "NEW_CATEGORIES_FAIL";


export const ALL_MAINCATEGORIES_REQUEST = "ALL_MAINCATEGORIES_REQUEST";
export const ALL_MAINCATEGORIES_SUCCESS = "ALL_MAINCATEGORIES_SUCCESS";
export const ALL_MAINCATEGORIES_FAIL = "ALL_MAINCATEGORIES_FAIL";

export const NEW_MAINCATEGORIES_REQUEST = "NEW_MAINCATEGORIES_REQUEST";
export const NEW_MAINCATEGORIES_SUCCESS = "NEW_MAINCATEGORIES_SUCCESS";
export const NEW_MAINCATEGORIES_RESET = "NEW_MAINCATEGORIES_RESET";
export const NEW_MAINCATEGORIES_FAIL = "NEW_MAINCATEGORIES_FAIL";


export const ALL_SUBCATEGORIES_REQUEST = "ALL_SUBCATEGORIES_REQUEST";
export const ALL_SUBCATEGORIES_SUCCESS = "ALL_SUBCATEGORIES_SUCCESS";
export const ALL_SUBCATEGORIES_FAIL = "ALL_SUBCATEGORIES_FAIL";

export const NEW_SUBCATEGORIES_REQUEST = "NEW_SUBCATEGORIES_REQUEST";
export const NEW_SUBCATEGORIES_SUCCESS = "NEW_SUBCATEGORIES_SUCCESS";
export const NEW_SUBCATEGORIES_RESET = "NEW_SUBCATEGORIES_RESET";
export const NEW_SUBCATEGORIES_FAIL = "NEW_SUBCATEGORIES_FAIL";

export const ALL_CHILDSUBCATEGORIES_REQUEST = "ALL_CHILDSUBCATEGORIES_REQUEST";
export const ALL_CHILDSUBCATEGORIES_SUCCESS = "ALL_CHILDSUBCATEGORIES_SUCCESS";
export const ALL_CHILDSUBCATEGORIES_FAIL = "ALL_CHILDSUBCATEGORIES_FAIL";

export const NEW_CHILDSUBCATEGORIES_REQUEST = "NEW_CHILDSUBCATEGORIES_REQUEST";
export const NEW_CHILDSUBCATEGORIES_SUCCESS = "NEW_CHILDSUBCATEGORIES_SUCCESS";
export const NEW_CHILDSUBCATEGORIES_RESET = "NEW_CHILDSUBCATEGORIES_RESET";
export const NEW_CHILDSUBCATEGORIES_FAIL = "NEW_CHILDSUBCATEGORIES_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

